name: Daily Subscription Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_subscriptions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Build and test
        run: |
          dotnet build
          dotnet test

      - name: Run subscription update service
        run: |
          dotnet run --project Expensier.Domain.csproj -- "Expensier.Domain.Services.Subscriptions.SubscriptionService.UpdateSubscriptionDate"
